spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://production-db:3306/ticket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver