security:
  extensible-enabled: true
  cors-enabled: true
  csrf-enabled: false
  public-endpoints:
    - "/api/v1/users/sign-up"
    - "/api/v1/auth/issueToken"
  jwt:
    secret: Rm9ySldUR2VuZXJhdGlvbkFuZEl0U2hvdWxkQmVWZXJ5TG9uZ0FuZFJhbmRvbTEyMyFAI0A=
    access-expiration: 3600

logging:
  level:
    org.springframework.security: DEBUG
