spring:
  security:
    user:
      name: user
      password: 1234

security:
  extensible-enabled: true
  cors-enabled: false
  csrf-enabled: false
  public-endpoints:
    - "/api/v1/users/sign-up"
    - "/api/v1/sellers/sign-up"
  jwt:
    secret: Rm9ySldUR2VuZXJhdGlvbkFuZEl0U2hvdWxkQmVWZXJ5TG9uZ0FuZFJhbmRvbTEyMyFAI0A=
    access-expiration: 3600

logging:
  level:
    root: INFO
    org.yechan: DEBUG

