spring:
  security:
    user:
      name: user
      password: 1234

security:
  extensible-enabled: true
  cors-enabled: false
  csrf-enabled: false
  public-endpoints:
    - "/api/v1/users/sign-up"


logging:
  level:
    root: INFO
    org.yechan: DEBUG

